version: '3.8'
services:
  app:
    container_name: "hireusapp"
    depends_on:
      - Mongo
    image: "jaketracewell/hireusapp"
    restart: "always"
    build: "."
    #port syntax= local port:app port
    ports:
      - "3002:3002"
    expose:
      - 3002
  Mongo:
    container_name: "hireusdb"
    image: "mongo"
# command:
    volumes:
      - ./data:/data/inquiries
    ports:
      - "27017:27017"
    expose:
      - 27017